name: simula_tools_20200312
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.1=py_0
  - bokeh=2.0.0=py38h32f6830_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38h32f6830_1
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38h32f6830_1001
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py38h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=64.2=he1b5a44_1
  - importlib-metadata=1.5.0=py38h32f6830_1
  - importlib_metadata=1.5.0=1
  - ipykernel=5.1.4=py38h5ca1d4c_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py38h32f6830_1
  - jinja2=2.11.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py_2
  - jupyter_client=6.0.0=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=2.0.1=py_0
  - jupyterlab_server=1.0.7=py_0
  - kiwisolver=1.1.0=py38hbf85e49_1
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.34.0=h516909a_0
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - markupsafe=1.1.1=py38h1e0a361_1
  - matplotlib=3.2.0=1
  - matplotlib-base=3.2.0=py38h250f245_1
  - mistune=0.8.4=py38h516909a_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=hf484d3e_1002
  - nodejs=13.9.0=h10a4023_0
  - notebook=6.0.3=py38_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py38h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h516909a_0
  - packaging=20.1=py_0
  - pandas=1.0.2=py38hcb8c335_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38h9776b28_1
  - pip=20.0.2=py_2
  - plotly=4.5.4=pyh8c360ce_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py38hcca6a23_1
  - pyrsistent=0.15.7=py38h516909a_0
  - python=3.8.2=h9d8adfe_4_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyyaml=5.3=py38h516909a_0
  - pyzmq=19.0.0=py38h1768529_0
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.7.1=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=hf8c457e_0
  - retrying=1.3.3=py_2
  - send2trash=1.5.0=py_0
  - setuptools=46.0.0=py38h32f6830_2
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py38h1e0a361_1
  - traitlets=4.3.3=py38h32f6830_1
  - typing_extensions=3.7.4.1=py38_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py38_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - gapminder==0.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1

